## Here will go the production elisp copied from various frags
## The .el files in the frags working directories
## The various frags will be assembled here with an mpt- prefix
## The mpt- prefix allows this project to be easily distinguishable in the
## final destination directory, ~/.emacs or the like 

SRCPT=../frags/periodic-table-1.0
SRCCC=../frags/chemical-compounds-1.0.2
SRCDB=../frags/terminalperiodictable-main

.el: $(SRCPT) $(SRCCC)
	cp $(SRCDIR)/$(FNAME).el .

